version: "3.7"

services:
  moin:
    #image: moinmoin:1.9.11-debug
    build: .
    ports:
      - 8080:8080
    restart: always
    # volumes:
    #   - type: bind
    #     source: /var/lib/moinmoin/vigor/data
    #     target: /opt/share/moin/data
  
      
  
