version: "3.7"

services:
  moin:
    #image: moinmoin:1.9.11-debug
    build:
      context: .
      dockerfile: moinmoin/Dockerfile.debug
    ports:
      - 8080:8080
    restart: always
    volumes:
      - type: bind
        source: /tmp/moindata
        target: /opt/share/moin/data

  backuprestore:
    #image: docker.io/diepes/backuprestore:latest
    build: 
      context: dbbackup
      dockerfile: Dockerfile-BackupRestore
    env_file:
      aws_credentials.env
    environment:
      - T=Test-docker-compose
      #- AWS_DEFAULT_REGION=us-west-2
    volumes:
      - type: bind
        source: /tmp/moindata
        target: /opt/share/moin/data
